### ISSUE TITLE
How we will use already saved credit card ?

### ISSUE THREAD

**Issue by banandam** [fontera/peach-oppwa#1]

**Comment by rootindex** [comment]
Hi @banandam 

This was written two years ago as a thought experiment.

It does look like I did not implement the peace of code required.

Looking at the documentation 

https://peachpayments.docs.oppwa.com/tutorials/server-to-server/one-click-payment-guide

**Comment by rootindex** [comment]
Using it will require a new class similar to these:
https://github.com/rootindex/peach-oppwa/tree/4b940ff95e06e462f228e6cbf99b5bcb9d6442cc/Cards

**Comment by banandam** [comment]
Thanks for your reply.
